import {
  Item1,
  Item10,
  Item11,
  Item12,
  Item2,
  Item3,
  Item4,
  Item5,
  Item6,
  Item7,
  Item8,
  Item9,
} from "./assets";
import { Product } from "./types";

export const sofas = [
  {
    image: Item1,
    heading: "Savanna Sofa",
    content:
      "Made from rich mahogany wood and tribal-inspired patterns, it invites you to combine comfort and style with the essence of Africa.",
  },
  {
    image: Item2,
    heading: "Baobab Sofa",
    content:
      "Our timber carved sofas are not just pieces of furniture; they’re crafted from sustainable fine wood, each detail carefully chosen to bring nature’s warmth into your home.",
  },
  {
    img: Item3,
    heading: "Zephyr Sofa",
    content:
      "Featuring sleek, chunky wooden arms and plush upholstery, it combines modern craftsmanship with a sophisticated rustic style.",
  },
];

export const products = [
  {
    image: Item1,
    name: "Kilimanjaro",
    description: "Wooden living room armchair",
    price: 85000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item2,
    name: "Kente",
    description: "Deep seat cushion armchair",
    price: 65000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item3,
    name: "Tonga",
    description: "Wooden living room armchair",
    price: 100000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item4,
    name: "Serengeti",
    description: "Wool cushion with wooden base",
    price: 90000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item5,
    name: "Timbuktu",
    description: "Wooden living room armchair",
    price: 200000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item6,
    name: "Masai sofa",
    description: "Soft long sofa",
    price: 250000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item7,
    name: "Amina",
    description: "Cushioned armchair",
    price: 35000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item8,
    name: "Oba",
    description: "Soft royal elegance",
    price: 300000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item9,
    name: "Kambili",
    description: "Home elegance and practicality",
    price: 45000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item10,
    name: "Adunni",
    description: "Modern comfort to any living space",
    price: 80000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item11,
    name: "Baobab",
    description: "Wooden stylish and versatile seating",
    price: 250000,
    isFavorite: false,
    isNew: true,
  },
  {
    image: Item12,
    name: "Ife",
    description: "Simplicity and comfort",
    price: 85000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item1,
    name: "Zephyr",
    description: "Wooden living room armchair",
    price: 250000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item2,
    name: "Olu",
    description: "Sleek design and supportive comfort",
    price: 85000,
    isFavorite: false,
    isNew: false,
  },
  {
    image: Item4,
    name: "Savanah",
    description: "Wooden living room armchair",
    price: 200000,
    isFavorite: false,
    isNew: false,
  },
] satisfies Array<Product>;
